// solid-app/src/components/Counter.jsx
import { createSignal } from 'solid-js';

const Counter = () => {
  const [count, setCount] = createSignal(0);

  return (
    <button
      class="px-4 rounded-md border-2 border-gray-900 text-gray-900 text-lg"
      onClick={() => setCount(count() + 1)}
    >
      clicked {count()} time{count() !== 1 && 's'}
    </button>
  );
};

export default Counter;

// react-app/src/components/Counter.jsx
import React, { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  return (
    <button
      className="px-4 text-lg text-gray-900 border-2 border-gray-900 rounded-md"
      onClick={() => setCount(count + 1)}
    >
      clicked {count} time{count !== 1 && 's'}
    </button>
  );
};

export default Counter;
