// apps/vue-app/src/App.vue
<script>
import Counter from './components/Counter.vue';

export default {
  data: () => {
    return {};
  },
  components: {
    Counter,
  },
};
</script>

<template>
  <div class="flex flex-col items-center mt-10">
    <img src="./assets/vue.png" alt="vue" class="w-32 mb-1" />
    <Counter />
  </div>
</template>

// apps/preact-app/src/App.jsx
import { render, h } from 'preact';
import Counter from './components/Counter';
import preactLogo from './assets/preact.png';

import './index.scss';

export const App = () => (
  <div class="mt-10 flex flex-col items-center">
    <img src={preactLogo} alt="preact" class="h-32 w-32" />
    <Counter />
  </div>
);

export default (element) => {
  render(<App />, element);
};
