// react-app/src/components/Counter.jsx
import React, { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  return (
    <button
      className="px-4 text-lg text-gray-900 border-2 border-gray-900 rounded-md"
      onClick={() => setCount(count + 1)}
    >
      clicked {count} time{count !== 1 && 's'}
    </button>
  );
};

export default Counter;

// angular-app/src/app/components/counter/counter.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.scss'],
})
export class CounterComponent {
  @Input() count: number = 0;

  increment() {
    this.count++;
  }
}

<button
  class="px-4 text-lg text-gray-900 border-2 border-gray-900 rounded-md"
  (click)="increment()"
>
  clicked {{ count }} time{{ count == 1 ? "" : "s" }}
</button>
