// react-app/src/App.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import Counter from './components/Counter';
import reactLogo from './assets/react.png';
import './index.scss';

export const App = () => (
  <div className="flex flex-col items-center mt-10">
    <img src={reactLogo} alt="react" className="w-32 mb-1" />
    <Counter />
  </div>
);

export default (element) => {
  ReactDOM.render(<App />, element);
};

// apps/solid-app/src/App.jsx
import { render } from 'solid-js/web';
import Counter from './components/Counter';
import solidJs from './assets/solid.svg';
import './index.scss';

export const App = () => (
  <div class="mt-10 flex flex-col items-center">
    <img src={solidJs} alt="solid" class="h-32 w-32" />
    <Counter />
  </div>
);

export default (element) => {
  render(App, element);
};
